---
output: md_document
---
# Cherry Blossom Prediction
#### Authors: "Amelia Tang, Alex Yinan Guo, Nick Lisheng Mao"

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About 
TBU 

### Report 
The final report can be found here. 

### Dependencies 
TBU
A complete list of dependencies is available [here](https://github.com/aimee0317/cherry-blossom-prediction/blob/main/blossom.yaml).
<br> - Python 3.9.10 and Python packages:
<br> - pandas==1.4.0
<br> - numpy==1.21.5
<br> - altair_saver=0.5.0
<br> - altair=4.1.0
<br> - scikit-learn=1.0.2
<br> - catboost=1.0.4

## Usage

### Creating the environment

`conda env create --file blossom.yaml`

Run the following command from the environment where you installed
JupyterLab.

`conda install nb_conda_kernels`

If you are a windows user, run the following command inside the newly
created environment to install vega-lite.

`npm install -g vega vega-cli vega-lite canvas`

For M1 mac users, make sure you are using the `x86` version of conda and
not the `arm64` version. See
[here](https://github.com/conda-forge/miniforge#miniforge3) and
[here](https://github.com/mwidjaja1/DSOnMacARM/blob/main/README.md) for
more info.

### References